In [1]:
import random
from TradingBackend.Backtester import Backtester
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/Nikesh/Desktop/TradingDataset/Bitmex/XBTUSD/1m OHLCV/XBTUSD.csv')
data.set_index('timestamp', inplace = True, drop = True)
data.index = pd.to_datetime(data.index)
data = (data.resample('30min')
               .agg({'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last', 'Volume':'sum'}))
data.sort_index(inplace=True)
data.fillna(method = 'bfill', inplace=True)

In [3]:
data['smaller_moving_average'] = data.Close.rolling(10).mean()
data['longer_moving_average'] = data.Close.rolling(20).mean()

In [4]:
def entry(self, i):
    if self.data.smaller_moving_average[i]>self.data.longer_moving_average[i] and self.data.smaller_moving_average[i-1]<=self.data.longer_moving_average[i-1]:
        return 1
    else:
        return 0

In [5]:
def monitor(self, i):
    if self.data.smaller_moving_average[i]<self.data.longer_moving_average[i] and self.data.smaller_moving_average[i-1]>=self.data.longer_moving_average[i-1]:
        return 1
    else:
        return 0

In [6]:
backtester = Backtester(data,lookback=25)

In [7]:
backtester.backtest(entry,monitor)

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=86325.0), HTML(value='')))

In [8]:
backtester.trade_history

,Trade_Type,Allocation_Count,Entry_Timestamp,Exit_Timestamp,Allocation_History,Total_Allocation,Exit_Price,Trade_PNL,Aggregate_PNL,Stopped,Trade_Duration,Trade_amount
0,Long,1,2015-10-05 15:00:00,2015-10-07 00:30:00,"[(2015-10-05 15:00:00, 239.6, 1)]",1,247.80,0.034224,0.034224,False,2010.0,103.422371
1,Long,1,2015-10-07 01:00:00,2015-10-07 06:00:00,"[(2015-10-07 01:00:00, 247.8, 1)]",1,246.72,-0.004358,-0.004358,False,300.0,102.971619
2,Long,1,2015-10-07 17:00:00,2015-10-07 19:00:00,"[(2015-10-07 17:00:00, 245.04, 1)]",1,245.34,0.001224,0.001224,False,120.0,103.097686
3,Long,1,2015-10-07 20:30:00,2015-10-07 21:30:00,"[(2015-10-07 20:30:00, 245.55, 1)]",1,244.00,-0.006312,-0.006312,False,60.0,102.446897
4,Long,1,2015-10-08 04:30:00,2015-10-08 10:00:00,"[(2015-10-08 04:30:00, 245.02, 1)]",1,243.15,-0.007632,-0.007632,False,330.0,101.665019
...,...,...,...,...,...,...,...,...,...,...,...,...
2594,Long,1,2020-09-04 19:30:00,2020-09-05 02:00:00,"[(2020-09-04 19:30:00, 10580.5, 1)]",1,10435.00,-0.013752,-0.013752,False,390.0,845.938763
2595,Long,1,2020-09-05 17:30:00,2020-09-05 18:30:00,"[(2020-09-05 17:30:00, 10124.5, 1)]",1,10149.50,0.002469,0.002469,False,60.0,848.027604
2596,Long,1,2020-09-06 01:30:00,2020-09-06 06:00:00,"[(2020-09-06 01:30:00, 10116.5, 1)]",1,10072.00,-0.004399,-0.004399,False,270.0,844.297338
2597,Long,1,2020-09-06 07:00:00,2020-09-06 08:30:00,"[(2020-09-06 07:00:00, 10170.0, 1)]",1,10235.00,0.006391,0.006391,False,90.0,849.693536
2598,Long,1,2020-09-06 09:00:00,2020-09-06 16:30:00,"[(2020-09-06 09:00:00, 10229.0, 1)]",1,10231.50,0.000244,0.000244,False,450.0,849.901204